[mavlink]
device = "/dev/ttyAMA2"
device2 = "/dev/ttyAMA3"
baud = 115200
mav_version = 2

[drops]
cruise_speed = 20
wind_speed = 5
wind_direction = 270
altitude = 60

[drops.beacon]
mass = 500
cd = 1
drop_course = 10
x_translation = -59.73950087139867
y_translation = 4.115124782150331

[drops.bottle]
mass = 500
cd = 0.2
drop_course = 10
x_translation = -66.33412669407143
y_translation = 1.4164683264821387

[camera]
resolution = [
    640,
    400,
]
K = [
    [
        692.45913591,
        0.0,
        635.07827968,
    ],
    [
        0.0,
        692.52565945,
        395.26189078,
    ],
    [
        0.0,
        0.0,
        1.0,
    ],
]
distortion = [
    -0.34219431,
    0.123526508,
    0.00470056821,
    -0.000109821856,
    -0.0211505931,
]

[dirs]
logs_dir = "media/logs"
photos_dir = "media/photos"
videos_dir = "media/videos"
zones_dir = "configuration/zones"
targets_file = "media/droniada_targets.json"

[system]
debug_mode = false

[zones]
search_zone_path = "sloszowa_droniada_T.poly"

[mission]
start_wp = 3
stop_wp = 4
is_bottle = true

[mission.loiter]
time = 15
alt = 60
radius = 50

[mission.ook]
duration_s = 10
candidates = [
    2.0,
    4.0,
    6.0,
    8,
    10,
    12,
    14,
    16,
    18,
    20,
    25,
    90,
    94,
    96,
    98,
    100,
]
min_confidence = 4.0
roi_size = 40
brightness_threshold = 220
